### ISSUE TITLE
Prices for minerals well below their true values in Jita

### ISSUE THREAD

**Issue by charliedimaggio** [Kyria/LazyBlacksmith#60]
Not sure if this a transient issue or ongoing but the prices for the minerals are set well below anything in new eden. Tritanium is at 2.20ISK per unit and Pyerite is at 1.04ISK. I think this is also affecting other items

**Comment by Kyria** [comment]
I see The forge when not logged in :) 

Actually, when you logs in, you have the ability to change the default price regions for items, thus you / your mate probably have Delve as default, and since I don't pull structures (yet?), that's probably the reason behind. 
And looking at the previous link I gave you, Delve has the price you mentioned.

To change the default region, you just have to log in, then go https://khon.space/account/ and change the regions in industry settings.
