### ISSUE TITLE
Raw materials incorrect

### ISSUE THREAD

**Issue by mebusvg** [Kyria/LazyBlacksmith#89]
When I switch to raw materials, it doesn't factor in the 1% reduction from a Sotiyo, thus making the raw materials (just before components) incorrect.

I checked ingame and with my own sheet.. Please do note that the reduction does not aplies to everything, example:

Scalar Capacitor Unit, 50 units will always require atleast 50 nanotransistors.

**Comment by Kyria** [comment]
@mebusvg do you maybe have an example ? 
Because i'm afraid I don't understand where/how I can check that issue, especially as I checked multiple time the 1% from Sotiyo (and all these structure) was taken into account (and is currently [here](https://github.com/Kyria/LazyBlacksmith/blob/master/lazyblacksmith/static/js/lb/evedata.js#L104)) ? 

Can you maybe provide an item, and the expected material (from the game, not from your sheet please), so I can have a look (I don't play anymore so it may be complicated to check it myself), any information would help to check where is the issue.

Thanks !

**Comment by mebusvg** [comment]
Sorry, it's correct... BPO's not the right settings, my apologies.

**Comment by Kyria** [comment]
no issues :) i'm glad you found what was wrong.
Thanks for the report anyway !
